import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import styles from "./layout.module.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  subsets: ["latin", "cyrillic"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["italic", "normal"]
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className} id="root">
        <Header />
        <div className={styles.layout}>
          <main className={styles["main-content"]}>{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
